phabricator:
  container_name: phabricator
  build: .
  volumes:
    - $PHABRICATOR_DIR:/phacility/phabricator
    - $ARCANIST_DIR:/phacility/arcanist
    - $LIBPHUTIL_DIR:/phacility/libphutil
  ports:
    - 80:80
  links:
    - mysql

mysql:
  container_name: phabricator_db
  image: mysql:5.6.27
  environment:
    MYSQL_ROOT_PASSWORD: password
