version: '2.1'
services:
  vault:
    image: vault:0.10.1
    restart: always
    cap_add:
     - IPC_LOCK
    ports:
     - "8200:8200"
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8200'
    volumes:
     - ./logs:/vault/logs
     - ./config:/vault/config
     - ./policy:/vault/policy
    command: server
    depends_on:
      - mysql
    links: 
      - mysql
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vault
      MYSQL_ROOT_HOST: '%'
    volumes:
     - ./data:/var/lib/mysql
