version: '2'
services:
  kafka:
    image: wurstmeister/kafka
    networks:
      - binding
    ports:
     - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181

networks:
  binding:
     external:
       name: zookeeper_zookeeper

