version: '2'
services:
  ignite:
    image: apacheignite/ignite
    networks:
      - binding
    ports:
     - 11211:11211
     - 47100:47100
     - 47500:47500
     - 49112:49112
    environment:
      CONFIG_URI: https://raw.githubusercontent.com/apache/ignite/master/examples/config/example-cache.xml
